import type { Account, ComercializadoraLead } from "./types";

const day = 24 * 60 * 60 * 1000;
const now = Date.now();
const iso = (offsetMs: number) => new Date(now - offsetMs).toISOString();

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "acc_001",
    kind: "consultor",
    fullName: "Marina Albuquerque",
    email: "marina@energia-sul.com.br",
    phone: "(51) 98821-4477",
    documentKind: "cnpj",
    document: "27.412.998/0001-22",
    companyName: "Energia Sul Consultoria LTDA",
    address: "Av. Carlos Gomes, 1340, sala 802 — Boa Vista — Porto Alegre/RS — CEP 90480-001",
    createdAt: iso(2 * 60 * 60 * 1000),
    status: "nova",
    active: true,
    payment: { status: "nao_iniciado" },
    history: [{ id: "h1", at: iso(2 * 60 * 60 * 1000), label: "Cadastro recebido" }],
  },
  {
    id: "acc_002",
    kind: "consultor",
    fullName: "Renato Vasconcelos",
    email: "renato.v@vsltrade.com",
    phone: "(11) 99412-0091",
    documentKind: "cpf",
    document: "418.220.991-04",
    createdAt: iso(8 * 60 * 60 * 1000),
    status: "nova",
    active: true,
    payment: { status: "nao_iniciado" },
    history: [{ id: "h1", at: iso(8 * 60 * 60 * 1000), label: "Cadastro recebido" }],
  },
  {
    id: "acc_003",
    kind: "consultor",
    fullName: "Camila Toledo",
    email: "camila@toledopartners.com.br",
    phone: "(31) 98174-2200",
    documentKind: "cnpj",
    document: "44.010.221/0001-89",
    companyName: "Toledo Partners Energia",
    address: "Rua Pernambuco, 1500, conj 14 — Funcionários — Belo Horizonte/MG — CEP 30130-150",
    createdAt: iso(1 * day),
    status: "nova",
    active: true,
    payment: { status: "trial", nextDueAt: iso(-29 * day) },
    history: [{ id: "h1", at: iso(1 * day), label: "Cadastro recebido" }],
  },
  {
    id: "acc_004",
    kind: "consultor",
    fullName: "Felipe Andrade",
    email: "felipe.andrade@nexenergy.com.br",
    phone: "(48) 99155-7732",
    documentKind: "cnpj",
    document: "31.220.487/0001-04",
    companyName: "Nex Energy Consultoria",
    address: "Rua Lauro Linhares, 770, sala 301 — Trindade — Florianópolis/SC — CEP 88036-002",
    createdAt: iso(7 * day),
    approvedAt: iso(5 * day),
    status: "criada",
    active: true,
    payment: {
      status: "em_dia",
      plan: "Plano Profissional",
      monthlyAmount: 480,
      nextDueAt: iso(-22 * day),
      lastPaidAt: iso(8 * day),
    },
    history: [
      { id: "h1", at: iso(7 * day), label: "Cadastro recebido" },
      { id: "h2", at: iso(5 * day), label: "Conta aprovada", by: "adminpulse" },
      { id: "h3", at: iso(2 * day), label: "Pagamento confirmado" },
    ],
  },
  {
    id: "acc_005",
    kind: "consultor",
    fullName: "Joana Prado",
    email: "joana@pradoassessoria.com",
    phone: "(21) 98899-1245",
    documentKind: "cpf",
    document: "302.881.470-19",
    createdAt: iso(14 * day),
    approvedAt: iso(12 * day),
    status: "criada",
    active: true,
    payment: {
      status: "pendente",
      plan: "Plano Inicial",
      monthlyAmount: 280,
      nextDueAt: iso(3 * day),
      lastPaidAt: iso(33 * day),
    },
    history: [
      { id: "h1", at: iso(14 * day), label: "Cadastro recebido" },
      { id: "h2", at: iso(12 * day), label: "Conta aprovada", by: "adminpulse" },
      { id: "h3", at: iso(3 * day), label: "Pagamento pendente — fatura emitida" },
    ],
  },
  {
    id: "acc_006",
    kind: "consultor",
    fullName: "Pedro Hauer",
    email: "phauer@meridiumenergia.com.br",
    phone: "(41) 99812-3300",
    documentKind: "cnpj",
    document: "19.870.554/0001-41",
    companyName: "Meridium Energia",
    address: "Av. Sete de Setembro, 4204, conj 1201 — Batel — Curitiba/PR — CEP 80250-210",
    createdAt: iso(40 * day),
    approvedAt: iso(38 * day),
    status: "criada",
    active: false,
    payment: {
      status: "atrasado",
      plan: "Plano Profissional",
      monthlyAmount: 480,
      nextDueAt: iso(12 * day),
      lastPaidAt: iso(48 * day),
    },
    history: [
      { id: "h1", at: iso(40 * day), label: "Cadastro recebido" },
      { id: "h2", at: iso(38 * day), label: "Conta aprovada", by: "adminpulse" },
      { id: "h3", at: iso(6 * day), label: "Conta desativada", by: "adminpulse" },
    ],
  },
  {
    id: "acc_007",
    kind: "consultor",
    fullName: "Larissa Vieira",
    email: "larissa@vieiraenergia.com.br",
    phone: "(85) 99182-4471",
    documentKind: "cpf",
    document: "510.114.220-87",
    createdAt: iso(60 * day),
    approvedAt: iso(58 * day),
    status: "criada",
    active: true,
    payment: {
      status: "em_dia",
      plan: "Plano Profissional",
      monthlyAmount: 480,
      nextDueAt: iso(-18 * day),
      lastPaidAt: iso(12 * day),
    },
    history: [
      { id: "h1", at: iso(60 * day), label: "Cadastro recebido" },
      { id: "h2", at: iso(58 * day), label: "Conta aprovada", by: "adminpulse" },
    ],
  },
];

export const MOCK_LEADS: ComercializadoraLead[] = [
  {
    id: "lead_001",
    fullName: "Bruno Sartori",
    email: "bruno@energroup.com.br",
    phone: "(11) 98442-7711",
    requestedAt: iso(3 * 60 * 60 * 1000),
    status: "aguardando",
    history: [{ id: "h1", at: iso(3 * 60 * 60 * 1000), label: "Solicitação recebida" }],
  },
  {
    id: "lead_002",
    fullName: "Ana Lúcia Mendonça",
    email: "ana.mendonca@vortexenergia.com",
    phone: "(11) 99888-2244",
    requestedAt: iso(1 * day),
    status: "em_contato",
    history: [
      { id: "h1", at: iso(1 * day), label: "Solicitação recebida" },
      { id: "h2", at: iso(20 * 60 * 60 * 1000), label: "Marcada como em contato", by: "adminpulse" },
    ],
  },
  {
    id: "lead_003",
    fullName: "Eduardo Bianchi",
    email: "eduardo@axisenergia.com.br",
    phone: "(31) 98741-3333",
    requestedAt: iso(9 * day),
    status: "convertida",
    history: [
      { id: "h1", at: iso(9 * day), label: "Solicitação recebida" },
      { id: "h2", at: iso(7 * day), label: "Marcada como em contato", by: "adminpulse" },
      { id: "h3", at: iso(2 * day), label: "Marcada como convertida", by: "adminpulse" },
    ],
  },
  {
    id: "lead_004",
    fullName: "Tatiana Rosso",
    email: "trosso@sinerguia.com.br",
    phone: "(51) 98112-9988",
    requestedAt: iso(20 * day),
    status: "perdida",
    history: [
      { id: "h1", at: iso(20 * day), label: "Solicitação recebida" },
      { id: "h2", at: iso(15 * day), label: "Marcada como em contato", by: "adminpulse" },
      { id: "h3", at: iso(4 * day), label: "Marcada como perdida", by: "adminpulse" },
    ],
  },
];
